/**
 * Created by gonghuihui on 16/12/7.
 */

module.exports = {
    financecode: 'JR201612190009',

    traderVerify: {
        financeMoney: '100',
        time: '60',
        amount: '2',
        place: '山西大同',
        origin: '山西原煤',
        price: '345',
        index: '地位热值、硫份',
    },

    saleVerify:{
        updownStream: '上下游相关签约单位信息补充',
        operationMode: '业务操作模式介绍',
        logistics:'物流/仓储地信息补充',
        another:'其他补充说明',
        supplyMaterial:'需要补充材料',
    },

    investigatorVerify:{
        weCompany: '慧慧公司',
        financeMoney: '100',
        financePeriod: '60',
        interestRate: '0.1',
        upstream: '上游签约单位',
        downstream: '下游签约单位',
        transport: '运输方',
        transitPort: '中转港口全称',
        qualityInspect: '质量检验单位',
        quantityInspect: '数量检验单位',
        historyCoperation: '历史合作情况',
        mainInformation: '业务主要信息',
        goodsCirculation: '货物流转',
        riskPoint: '业务风险点',
        credit: '履约信用及能力评估',
        opinions: '综合意见',
    },

    supervisorVerify:{
        warehouseProperty: '仓库性质',
        warehouseAddress: '仓库地址',
        historyCooperation: '我方与港口的历史合作状况',
        managerCondition: '经营及堆存状况',
        standardDegree: '保管及进出库流程规范程度',
        Coordination: '监管配合状况',
        scheme: '监管方案',
        conclusion: '结论',
    },

    riskVerify:{
        distributionCapability: '分销能力评估',
        operationalRisk: '业务操作风险点',
        controlScheme: '风控方案',
        controlConclusion: '风控结论',

        signAddress: '上海浦东',
        shipName: '泰坦尼克号',
        shipTime: 'h498',
        unloadPlace: '武汉汉口码头',
        addreviation:'汉',
        tonnage: '5100',
        deliveryPlace: '安徽合肥',
        variety: '原煤',
        quantity:'5000',
        quantityRemarks: '无',
        hot:'3500',
        liu:'8',
        anotherQuality:'无',
        qualityInspect:'质量验收标准',
        quanityInspect:'数量验收标准',
        settlementPrice:'100',
        billPrice:'200',
        billQuanity:'5000',
        buyerSum:'1000000',
        specialAgreement:'无特别约定',
        contractAppendcy: '5',
        contractName:'仓押具体事项的相关约定',
        buyerCompany:'安徽电厂',
        buyer:'许文强',
        buyerPhone:'13811111111',
        buyerEmail:'11111111@qq.com',
        buyerComAddress:'安徽合肥',
        buyerLegalRepresent:'许三多',
        buyerBank:'招商银行',
        buyerBankAccount:'1111111111111111',
        sellerCom:'河南煤炭有限公司',
        seller:'龚慧慧',
        sellerPhone:'13988888888',
        sellerEmail:'88888888@qq.com',
        sellerComAddress:'河南郑州',
        sellerLegalRepresent:'梅中客',
        sellerBank:'中国银行',
        sellerBankAccount:'8888888888888888',

        buyAdress2:'安徽合肥',
        paymentPeriods2:'7',
        finalSum2:'1000000',
        bond2: '30000',
        supplyName2: '河南煤炭',
        contractNum2:'234364576575432',
        quantityInspectTonnage2: '5000',
    }
}