FROM ubuntu-1404
MAINTAINER hary <94093146@qq.com>

ADD site/dist/ /nginx/finance/static/site
ADD admin/dist/ /nginx/finance/static/admin

WORKDIR /nginx/finance/static

VOLUME  /nginx/finance/static
