
CREATE TABLE `t_finance_order` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `create_man_id` varchar(255) DEFAULT NULL,
  `create_time` datetime DEFAULT NULL,
  `last_update_man_id` varchar(255) DEFAULT NULL,
  `last_update_time` datetime DEFAULT NULL,
  `apply_company_name` varchar(60) NOT NULL,
  `apply_type` varchar(20) NOT NULL,
  `apply_user_name` varchar(50) DEFAULT NULL,
  `apply_user_phone` varchar(50) NOT NULL,
  `approve_state` varchar(30) NOT NULL,
  `approve_state_id` int(11) NOT NULL,
  `business_amount` decimal(20,2) DEFAULT NULL,
  `coal_quantity_index` text DEFAULT NULL,
  `coal_source` varchar(120) DEFAULT NULL,
  `comments` text,
  `downstream_contract_company` varchar(120) DEFAULT NULL,
  `end_time` datetime DEFAULT NULL,
  `expect_date` int(11) NOT NULL,
  `financing_amount` decimal(20,2) DEFAULT NULL,
  `market_price` decimal(10,2) DEFAULT NULL,
  `our_contract_company` varchar(120) DEFAULT NULL,
  `procurement_price` decimal(10,2) DEFAULT NULL,
  `selling_price` decimal(10,2) DEFAULT NULL,
  `source_id` varchar(100) NOT NULL,
  `storage_location` varchar(120) DEFAULT NULL,
  `terminal_server` varchar(120) DEFAULT NULL,
  `transfer_port` varchar(120) DEFAULT NULL,
  `transport_mode` varchar(30) DEFAULT NULL,
  `upstream_resource` varchar(120) DEFAULT NULL,
  `user_id` int(11) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `UK_g6enb55whaik9mab9598yn0rf` (`source_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE `t_finance_order_contract` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `create_man_id` varchar(255) DEFAULT NULL,
  `create_time` datetime DEFAULT NULL,
  `last_update_man_id` varchar(255) DEFAULT NULL,
  `last_update_time` datetime DEFAULT NULL,
  `attachment_names` varchar(520) DEFAULT NULL,
  `attachment_number` int(11) DEFAULT NULL,
  `buyer_bank_account` varchar(120) DEFAULT NULL,
  `buyer_bank_name` varchar(120) DEFAULT NULL,
  `buyer_company_address` varchar(220) DEFAULT NULL,
  `buyer_company_name` varchar(120) DEFAULT NULL,
  `buyer_legal_person` varchar(60) DEFAULT NULL,
  `buyer_linkman_email` varchar(120) DEFAULT NULL,
  `buyer_linkman_name` varchar(60) DEFAULT NULL,
  `buyer_linkman_phone` varchar(50) DEFAULT NULL,
  `buyer_settlement_money` decimal(20,2) DEFAULT NULL,
  `cash_deposit` decimal(20,2) DEFAULT NULL,
  `coal_amount` decimal(12,2) DEFAULT NULL,
  `coal_index` text,
  `coal_ton` decimal(12,2) DEFAULT NULL,
  `coal_type` varchar(120) DEFAULT NULL,
  `contract_no` varchar(100) NOT NULL,
  `delivery_place` varchar(220) DEFAULT NULL,
  `finance_id` bigint(20) NOT NULL,
  `payment_period` int(11) DEFAULT NULL,
  `purchase_place` varchar(220) DEFAULT NULL,
  `quality_acceptance_criteria` text,
  `quality_remark` text,
  `quantity_acceptance_criteria` text,
  `quantity_remark` text,
  `seller_bank_account` varchar(120) DEFAULT NULL,
  `seller_bank_name` varchar(120) DEFAULT NULL,
  `seller_company_address` varchar(220) DEFAULT NULL,
  `seller_company_name` varchar(120) DEFAULT NULL,
  `seller_legal_person` varchar(60) DEFAULT NULL,
  `seller_linkman_email` varchar(120) DEFAULT NULL,
  `seller_linkman_name` varchar(60) DEFAULT NULL,
  `seller_linkman_phone` varchar(50) DEFAULT NULL,
  `seller_receipt_amount` decimal(12,2) DEFAULT NULL,
  `seller_receipt_money` decimal(20,2) DEFAULT NULL,
  `seller_receipt_price` decimal(10,2) DEFAULT NULL,
  `settlement_amount` decimal(12,2) DEFAULT NULL,
  `settlement_price` decimal(10,2) DEFAULT NULL,
  `ship_name` varchar(120) DEFAULT NULL,
  `ship_no` varchar(120) DEFAULT NULL,
  `sign_date` date DEFAULT NULL,
  `sign_place` varchar(220) DEFAULT NULL,
  `special_remark` text DEFAULT NULL,
  `type` int(11) NOT NULL,
  `unload_place` varchar(220) DEFAULT NULL,
  `unload_place_short` varchar(220) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `UK_ar2nid9hkaxh09l3i0lf3hx48` (`contract_no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE `t_finance_order_investigator_info` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `create_man_id` varchar(255) DEFAULT NULL,
  `create_time` datetime DEFAULT NULL,
  `last_update_man_id` varchar(255) DEFAULT NULL,
  `last_update_time` datetime DEFAULT NULL,
  `apply_company_name` varchar(120) DEFAULT NULL,
  `approve_state` varchar(30) DEFAULT NULL,
  `approve_state_id` int(11) DEFAULT NULL,
  `business_risk_point` text,
  `business_start_time` datetime DEFAULT NULL,
  `business_transfer_info` TEXT DEFAULT NULL,
  `downstream_contract_company` varchar(120) DEFAULT NULL,
  `final_conclusion` text,
  `finance_id` bigint(20) NOT NULL,
  `financing_amount` decimal(20,2) DEFAULT NULL,
  `financing_period` int(11) DEFAULT NULL,
  `historical_cooperation_detail` TEXT DEFAULT NULL,
  `interest_rate` decimal(5,2) DEFAULT NULL,
  `main_business_information` TEXT DEFAULT NULL,
  `need_supply_material` int(11) NOT NULL,
  `our_contract_company` varchar(120) DEFAULT NULL,
  `performance_credit_ability_eval` text,
  `quality_inspection_unit` varchar(120) DEFAULT NULL,
  `quantity_inspection_unit` varchar(120) DEFAULT NULL,
  `supply_material_introduce` text,
  `terminal_server` varchar(120) DEFAULT NULL,
  `transit_port` varchar(120) DEFAULT NULL,
  `transport_party` varchar(120) DEFAULT NULL,
  `upstream_contract_company` varchar(120) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `UK_5fk8chux90a1u2oqh98w5rwsj` (`finance_id`)
) ENGINE=InnoDB AUTO_INCREMENT=16 DEFAULT CHARSET=utf8;


CREATE TABLE `t_finance_order_riskmanager_info` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `create_man_id` varchar(255) DEFAULT NULL,
  `create_time` datetime DEFAULT NULL,
  `last_update_man_id` varchar(255) DEFAULT NULL,
  `last_update_time` datetime DEFAULT NULL,
  `approve_state` varchar(30) DEFAULT NULL,
  `approve_state_id` int(11) DEFAULT NULL,
  `business_risk_point` text,
  `distribution_ability_eval` text,
  `edit_contract` int(11) NOT NULL,
  `final_conclusion` text,
  `finance_id` bigint(20) NOT NULL,
  `need_supply_material` int(11) NOT NULL,
  `payment_situation_eval` text DEFAULT NULL,
  `risk_control_scheme` text,
  `supply_material_introduce` text,
  PRIMARY KEY (`id`),
  UNIQUE KEY `UK_krvryyysusj5h2283e9j6xaji` (`finance_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE `t_finance_order_salesman_info` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `create_man_id` varchar(255) DEFAULT NULL,
  `create_time` datetime DEFAULT NULL,
  `last_update_man_id` varchar(255) DEFAULT NULL,
  `last_update_time` datetime DEFAULT NULL,
  `approve_state` varchar(30) DEFAULT NULL,
  `approve_state_id` int(11) DEFAULT NULL,
  `business_model_introduce` text,
  `contract_companies_info_supply` text,
  `finance_id` bigint(20) NOT NULL,
  `logistics_storage_info_supply` text,
  `need_supply_material` int(11) NOT NULL,
  `other_info_supply` text,
  `supply_material_introduce` text,
  PRIMARY KEY (`id`),
  UNIQUE KEY `UK_8bpnaokbijty2d0db9vjhpnms` (`finance_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE `t_finance_order_supervisor_info` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `create_man_id` varchar(255) DEFAULT NULL,
  `create_time` datetime DEFAULT NULL,
  `last_update_man_id` varchar(255) DEFAULT NULL,
  `last_update_time` datetime DEFAULT NULL,
  `approve_state` varchar(30) DEFAULT NULL,
  `approve_state_id` int(11) DEFAULT NULL,
  `final_conclusion` text,
  `finance_id` bigint(20) NOT NULL,
  `historical_cooperation_detail` varchar(1020) DEFAULT NULL,
  `need_supply_material` int(11) NOT NULL,
  `operating_storage_detail` text,
  `port_standard_degree` text,
  `storage_address` varchar(220) DEFAULT NULL,
  `storage_location` varchar(120) DEFAULT NULL,
  `storage_property` varchar(120) DEFAULT NULL,
  `supervision_cooperate_detail` text,
  `supervision_scheme` text,
  `supply_material_introduce` text,
  PRIMARY KEY (`id`),
  UNIQUE KEY `UK_ta4japa2kqpk7dot785derkb2` (`finance_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE `t_finance_userlogin_log` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `create_time` datetime NOT NULL,
  `user_id` varchar(30) NOT NULL,
  `username` varchar(30) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE `t_finance_number` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `create_date` date DEFAULT NULL,
  `type` varchar(30) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
