CREATE TABLE `T_finance_apply_info` (
  `id` int(11) NOT NULL COMMENT '主键',
  `userId` int(11) DEFAULT NULL COMMENT '用户id ',
  `applyType` varchar(45) DEFAULT NULL COMMENT '申请类型：\n煤易融：MYR\n煤易贷:   MYD\n煤易购:   MYG',
  `financingAmount` decimal(10,2) DEFAULT NULL COMMENT '拟融资金额（单位：万元）',
  `expectedDate` int(11) DEFAULT NULL COMMENT '拟使用资金时间（单位：天）',
  `businessAmount` decimal(15,2) DEFAULT NULL COMMENT '预期此笔业务量（单位：万吨）',
  `transportMode` varchar(45) DEFAULT NULL COMMENT '运输方式：\n海运\n汽运\n火运\n其他',
  `procurementPrice` decimal(10,2) DEFAULT NULL COMMENT '单吨采购价 (元/吨)',
  `upstreamResource` varchar(100) DEFAULT NULL COMMENT '上游资源方全称',
  `transferPort` varchar(100) DEFAULT NULL COMMENT '中转港口/地全称',
  `comments` varchar(200) DEFAULT NULL COMMENT '备注说明',
  `contractors` varchar(100) DEFAULT NULL COMMENT '签约单位全称',
  `downstreamContractors` varchar(100) DEFAULT NULL COMMENT '下游签约单位全称',
  `terminalServer` varchar(100) DEFAULT NULL COMMENT '用煤终端',
  `sellingPrice` decimal(10,2) DEFAULT NULL COMMENT '预计单吨销售价 (元/吨)',
  `storageLocation` varchar(100) DEFAULT NULL COMMENT '煤炭仓储地',
  `coalSources` varchar(100) DEFAULT NULL COMMENT '煤炭来源',
  `marketPrice` decimal(10,2) DEFAULT NULL COMMENT '单吨市场报价（元／吨）',
  `approveState` varchar(30) DEFAULT NULL COMMENT '审批状态',
  `approveComments` varchar(200) DEFAULT NULL COMMENT '审批说明',
  `souceId` varchar(50) DEFAULT NULL COMMENT '流水号，编号',
  `applyDateTime` datetime DEFAULT NULL COMMENT '申请时间',
  `applyUserName` varchar(45) DEFAULT NULL COMMENT '申请人姓名',
  `applyCompanyName` varchar(45) DEFAULT NULL COMMENT '申请公司名称',
  `workFlowInstanceId` varchar(45) DEFAULT NULL COMMENT '工作流实例id',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COMMENT '申请信息表';